backend:
  name: github
  repo: cocodev-harvard/cocodev.org
  branch: master
  use_graphql: true

local_backend: true
site_url: "https://cocodev.netlify.app/"
display_url: "https://cocodev.netlify.app/"
logo_url: "https://cocodev.netlify.app/images/logo-abbreviation.svg"

media_folder: "static/images/"
public_folder: "images"

x-false-bool: &false-bool { widget: "boolean", default: false, }
x-opt-list: &opt-list { widget: "list", required: false, }
x-opt-str: &opt-str { widget: "string", required: false, }
x-req-str: &req-str { widget: "string", required: true, }
x-opt-md: &opt-md { widget: "markdown", }

x-title: &title { <<: *req-str , label: "Title", name: "title", }
x-subtitle: &subtitle { <<: *opt-str, label: "Subtitle", name: "subtitle", }
x-body: &body { label: "Body", name: "body", widget: "markdown", }
x-summary: &summary { label: "Summary", name: "summary", widget: "markdown", }

x-draft: &draft { <<: *false-bool, label: "Draft", name: "draft", }
x-featured: &featured { <<: *false-bool, label: "Featured", name: "featured", }

x-authors: &authors { <<: *opt-list, label: "Authors", name: "authors", }
x-tags: &tags { <<: *opt-list, label: "tags", name: "tags", }
x-categories: &categories { <<: *opt-list, label: "Categories", name: "categories", }
x-projects: &projects { <<: *opt-list, label: "Projects", name: "projects", }

x-featured-image: &featured-image
  label: "Featured Image"
  name: "image"
  required: false
  widget: "object"
  fields:
    - label: "Upload an image named: `featured.{jpg,png}`"
      name: "filename"
      widget: "image"
      default: "featured"
      required: false
      media_library:
        config:
          multiple: false
    - { <<: *opt-str, label: Caption, name: caption, }
    - { <<: *opt-str, label: Description for screen readers, name: alt_text, }
    - label: "Where's the focal point in the image? Smart, Center, TopLeft, Top, TopRight, Left, Right, BottomLeft, Bottom, BottomRight."
      name: focal_point
      widget: select
      required: false
      default: "Smart"
      options: ["Smart", "Center", "TopLeft", "Top", "TopRight", "Left", "Right", "BottomLeft", "Bottom", "BottomRight"]
    - { <<: *false-bool, label: Thumbnail Only?, name: preview_only, }

x-icon-links: &icon-links
  required: false
  widget: list
  fields:
    - {label: Link, name: link, widget: string}
    - label: Icon pack
      name: icon_pack
      widget: select
      multiple: false
      options:
        - {label: "None", value: ""}
        - {label: "Solid", value: "fas"}
        - {label: "Regular", value: "far"}
        - {label: "Brand", value: "fab"}
        - {label: "Academic", value: "ai"}
    - {label: Icon (see https://sourcethemes.com/academic/docs/page-builder/#icons), name: icon, widget: string}

collections:
  - name: authors
    label: Members
    label_singular: Member
    folder: "content/authors"
    path: "{{slug}}/_index"
    create: true  # Allow users to create new documents in this collection
    fields:  # The fields each document in this collection have
      - <<: *title
        label: "Name"
        hint: "Your first and family name are ideal."
      - label: "Avatar (upload an image named `avatar.{jpg,png}`)"
        name: "avatar_filename"
        widget: "image"
        default: "avatar"
        required: false
        media_library:
          config:
            multiple: false
      - { <<: *summary , name: bio, label: "Brief Description", hint: "About 2 tweets.", }
      - { <<: *body , label: "Full Description", hint: "Shown on your page.", }
      - label: "Interests (shown in About widget)"
        name: "interests"
        required: false
        widget: "list"
      - <<: *icon-links
        label: Social links
        name: social
      - label: "Organizations"
        name: "organizations"
        required: false
        widget: list
        hint: Organizations you belong to or are affiliated with.
        fields:
          - {label: Organization, name: name, widget: string, required: true}
          - {label: Link, name: url, widget: string, required: false}
      - label: "Education"
        name: "education"
        required: false
        widget: object
        fields:
          - label: "Degrees"
            name: "courses"
            required: false
            widget: list
            fields:
              - {label: Program, name: course, widget: string, required: true}
              - {label: Institution, name: institution, widget: string, required: true}
              - {label: Year, name: year, widget: number, valueType: int, required: false}
      - label: "User groups (only for organization websites)"
        name: "user_groups"
        widget: "select"
        multiple: true
        options:
          - { value: "Researchers", label: "Researchers", }
          - { value: "Administration", label: "Administration", }
          - { value: "Alumni", label: "Alumni", }
          - { value: "Postdocs", label: "Postodcs", }
          - { value: "Graduate Students", label: "Graduate Students", }
          - { value: "Undergraduate Students", label: "Undergraduate Students", }
  - name: publications
    label: "Publications"
    label_singular: Publication
    folder: "content/publication"
    path: "{{slug}}/index"
    summary: "{{fields.publication_short}} - {{fields.title}}"
    create: true
    sortable_fields: ["date", "title", "publication"]
    fields:
      - { <<: *req-str , label: "URL Key", name: slug, hint: "This should be something like... <first-author-last-name><year><first-title-word>."}
      - { <<: *title }
      # - <<: *subtitle
      - name: publication_types
        label: Publication Type
        widget: select
        multiple: true
        options:
        - { value: "0", label: Uncategorized Publication, }
        - { value: "1", label: Conference Publication, }
        - { value: "2", label: Journal Publication, }
        - { value: "3", label: Preprint, }
        - { value: "4", label: Report, }
        - { value: "5", label: Book, }
        - { value: "6", label: Book Section/Chapter, }
        - { value: "7", label: Thesis, }
        - { value: "8", label: Patent, }
      - {label: "Venue Publication Date", name: "date", widget: "datetime"}
      - { <<: *summary , name: abstract, label: Abstract }
      - label: "Publication Upload"
        name: "url_pdf"
        widget: "file"
        media_library:
          config:
            multiple: true
      - { <<: *draft }
      - { <<: *featured }
      - { <<: *authors }
      - { <<: *authors , name: author_notes, label: Author Notes }
      - { <<: *tags }
      # - <<: *categories
      - { <<: *projects }
      - { <<: *req-str, name: publication,  label: Venue }
      - { <<: *opt-str, name: publication_short , label: Venue Abbreviation, }
      - { <<: *opt-str , name: doi , label: DOI , }
      # - { <<: *opt-str , name: url_pdf, label: PDF URL, }
      - { <<: *opt-str , name: url_code, label: Code Repository, }
      - { <<: *opt-str , name: url_dataset, label: Dataset URL, }
      - { <<: *opt-str , name: url_poster, label: Poster URL, }
      - { <<: *opt-str , name: url_project, label: Project URL, }
      - { <<: *opt-str , name: url_slides, label: Slides URL, }
      - { <<: *opt-str , name: url_source, label: Source URL, }
      - { <<: *opt-str , name: url_video, label: Video URL, }
